name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest # TODO: Add macos-latest to matrix

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --all --verbose
    - name: Test
      run: cargo test --all --verbose
